#!/usr/bin/php
<?php

// comandos disponíveis:
//
// php atrium create-tables -> Roda todas as migrations
// php atrium add-users      -> Cria ou atualiza os usuários na tabela users

require __DIR__ . "/vendor/autoload.php";
$atrium = new App\Controller\AtriumController($argv);
die;
